manifest:
  remotes:
    - name: nrfconnect
      url-base: https://github.com/nrfconnect

  projects:
    - name: sdk-nrf
      remote: nrfconnect
      revision: v2.6.0
      import: true

  self:
    path: bthomev2-nrf52-zephyr
